### PR TITLE
fix build with vdr 2.7.1

### LINKED ISSUE #1: Build fails with vdr 2.7.1
GetEvent has been deprecated
- ref:
- http://git.tvdr.de/?p=vdr.git;a=commitdiff;h=8d82b050712de0db83ac3b28d04a59479b024622;hp=930e3b4200e0bdf46264ef663e6121264ef6e2e4

```
BUILD      vdr-plugin-eepg (target)
    TOOLCHAIN      manual
CC eepg.o
CC epghandler.o
CC equivhandler.o
CC util.o
make: Nothing to be done for 'install-i18n'.
CC eit2.o
epghandler.c: In member function 'virtual bool cEEpgHandler::HandleEitEvent(cSchedule*, const SI::EIT::Event*, uchar, uchar)':
epghandler.c:69:32: error: 'class cSchedule' has no member named 'GetEvent'; did you mean 'DelEvent'?
   69 |   const cEvent* ev = schedule->GetEvent(EitEvent->getEventId(),EitEvent->getStartTime());
      |                                ^~~~~~~~
      |                                DelEvent
epghandler.c:72:22: error: 'class cSchedule' has no member named 'GetEvent'; did you mean 'DelEvent'?
   72 |       ev = schedule->GetEvent(EitEvent->getEventId());
      |                      ^~~~~~~~
      |                      DelEvent
make: *** [Makefile:123: epghandler.o] Error 1
make: *** Waiting for unfinished jobs....
util.c: In member function 'virtual void util::cAddEventThread::Action()':
util.c:217:50: error: 'class cSchedule' has no member named 'GetEvent'; did you mean 'DelEvent'?
  217 |         cEvent *pEqvEvent = (cEvent *) schedule->GetEvent (event->EventID(), event->StartTime());
      |                                                  ^~~~~~~~
      |                                                  DelEvent
make: *** [Makefile:123: util.o] Error 1
equivhandler.c: In member function 'void cEquivHandler::updateEquivalent(cSchedules*, tChannelID, cEvent*)':
equivhandler.c:146:49: error: 'class cSchedule' has no member named 'GetEvent'; did you mean 'DelEvent'?
  146 |       cEvent *pEqvEvent = (cEvent *) pSchedule->GetEvent (pEvent->EventID(), pEvent->StartTime());
      |                                                 ^~~~~~~~
      |                                                 DelEvent
make: *** [Makefile:123: equivhandler.o] Error 1
eit2.c: In member function 'cEvent* SI::cEIT2::ProcessEitEvent(cSchedule*, const SI::EIT::Event*, uchar, uchar)':
eit2.c:35:42: error: 'class cSchedule' has no member named 'GetEvent'; did you mean 'DelEvent'?
   35 |   cEvent *pEvent = (cEvent *) pSchedule->GetEvent (EitEvent->getEventId (), EitEvent->getStartTime ());
      |                                          ^~~~~~~~
      |                                          DelEvent
eit2.c: In member function 'void SI::cEIT2::ProcessEventDescriptors(bool, int, SI::u_char, const SI::EIT::Event*, cEvent*, const tChannelID&)':
eit2.c:246:29: error: 'const class cSchedule' has no member named 'GetEvent'; did you mean 'DelEvent'?
  246 |         rEvent = rSchedule->GetEvent(tsed->getReferenceEventId());
      |                             ^~~~~~~~
      |                             DelEvent
make: *** [Makefile:123: eit2.o] Error 1
eepg.c: In member function 'virtual bool cFilterEEPG::GetThemesSKYBOX()':
eepg.c:872:23: warning: the address of 'cFilterEEPG::Themes' will never be NULL [-Waddress]
  872 |           if (Themes[i]) {
      |               ~~~~~~~~^
eepg.c:202:17: note: 'cFilterEEPG::Themes' declared here
  202 |   unsigned char Themes[MAX_THEMES][64];
      |                 ^~~~~~
eepg.c: In member function 'virtual void cFilterEEPG::WriteToSchedule(tChannelID, cSchedules*, unsigned int, unsigned int, unsigned int, char*, char*, short unsigned int, short unsigned int, short unsigned int, char, unsigned char)':
eepg.c:1327:30: error: 'class cSchedule' has no member named 'GetEvent'; did you mean 'DelEvent'?
 1327 |       Event = (cEvent *) ps->GetEvent (EventId); //since Nagra uses consistent EventIds, try this first
      |                              ^~~~~~~~
      |                              DelEvent
eepg.c:1332:32: error: 'class cSchedule' has no member named 'GetEvent'; did you mean 'DelEvent'?
 1332 |         Event = (cEvent *) ps->GetEvent (EventId, StartTime);
      |                                ^~~~~~~~
      |                                DelEvent
eepg.c: In member function 'void cFilterEEPG::ProcessPremiere(const u_char*&)':
eepg.c:3480:54: error: 'class cSchedule' has no member named 'GetEvent'; did you mean 'DelEvent'?
 3480 |               cEvent *pEvent = (cEvent *) pSchedule->GetEvent (EventId, -1);
      |                                                      ^~~~~~~~
      |                                                      DelEvent
make: *** [Makefile:123: eepg.o] Error 1
FAILURE: s/build vdr-plugin-eepg during make_target (package.mk)
```

### PR DESCRIPTION
**Pull request by heitbaum**
- fixes #1

### CODE REVIEW

**Comment by M-Reimer** [comment]
Sorry that this PR got missed. I had notifications disabled on this repo and now have already merged a different fix for this issue.

**Comment by heitbaum** [comment]
> Sorry that this PR got missed. I had notifications disabled on this repo and now have already merged a different fix for this issue.

all good - tested 0.0.7 - building fine.
